export const ApiRoute = {
  AuthCheck: '/users/check-token',
  AddFriend: '/users/:userId/add-friend/:friendId',
  AddSubscriber: '/subscribers/:userId/subscribe',
  CreateOrder: '/orders/trainings/:id/create-order',
  CreateCoachQuestionnaire: '/users/:id/create-coach-questionnaire',
  CreateUserQuestionnaire: '/users/:id/create-user-questionnaire',
  CreateUserApplication: '/applications/invite',
  CreateTraining: '/trainings/create',
  CreateTrainingFeedback: '/trainings/:id/create-feedback',
  DeleteFriend: '/users/:userId/delete-friend/:friendId',
  DeleteNotification: '/notifications/:id/delete',
  DeleteSubscriber: '/subscribers/:id/unsubscribe',
  DeleteTraining: '/trainings/:id/delete',
  DeleteUser: '/users/:id/delete',
  DeleteUserAvatar: '/users/:id/delete-avatar',
  DeleteQualificationFile: '/users/qualifications/:id/delete',
  EditTraining: '/trainings/:id/edit',
  EditUser: '/users/:id/edit',
  Login: '/users/sign-in',
  Logout: '/users/logout',
  MyFriend: '/users/:userId/my-friend/:friendId',
  Notifications: '/notifications',
  Orders: '/orders',
  Order: '/orders/:id',
  Subscribers: '/subscribers/:userId/subscribers',
  RangeFilters: '/trainings/range',
  ReadyUsers: '/users/is-ready',
  Register: '/users/sign-up',
  RefreshToken: '/users/refresh-token',
  RecommendedTrainings: '/trainings/recommended-trainings',
  Trainings: '/trainings',
  Training: '/trainings/:id',
  TrainingFeedbacks: '/trainings/:id/feedbacks',
  UpdateQualificationFile: '/users/qualifications/:id/update',
  UpdateUserApplication: '/applications/:applicationId/change-status',
  User: '/users/:id',
  Users: '/users',
  UserApplications: '/applications',
  UserBalance: '/users/:id/balance',
  UseUserBalance: '/users/:userId/balance/use/:trainingId',
  UserFriends: '/users/friends'
} as const;

export type ApiRouteType = (typeof ApiRoute)[keyof typeof ApiRoute];
