export enum Route {
  AuthCheck = 'check-token',
  Balance = ':userId/balance',
  Create = 'create',
  CreateOrder = ':id/create-order',
  CreateCoachQuestionnaire = ':userId/create-coach-questionnaire',
  CreateUserQuestionnaire = ':userId/create-user-questionnaire',
  CreateTrainingFeedback = ':id/create-feedback',
  DeleteTraining = ':id/delete',
  DeleteUser = ':userId/delete',
  DeleteUserAvatar = ':userId/delete-avatar',
  EditTraining = ':id/edit',
  EditUser = ':userId/edit',
  Feedbacks = ':id/feedbacks',
  Login = 'sign-in',
  Range = 'range',
  Register = 'sign-up',
  RefreshToken = 'refresh-token',
  Recommended = 'recommended-trainings',
  Root = '/',
  Training = ':id',
  User = ':userId'
};
