services:
  mongo-fitfriends:
    image: mongo:7.0
    container_name: files_database
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - files_data:/data/db
    networks:
      - 599c27540b41-network
  postgres-fitfriends:
    image: postgres:16.4
    container_name: fitfriends_database
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - fitfriends_data:/var/lib/postgresql/data
    networks:
      - 599c27540b41-network
networks:
  599c27540b41-network:
    name: 599c27540b41-network
    driver: bridge
volumes:
  files_data:
  fitfriends_data:
