# Create user.

POST http://localhost:5000/api/users/sign-up HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/png

< C:\Users\strim\Desktop\pro\avatar.jpg
--MyBoundary
Content-Disposition: form-data; name="name"

Александр
--MyBoundary
Content-Disposition: form-data; name="email"

alex@gmail.com
--MyBoundary
Content-Disposition: form-data; name="password"

123456
--MyBoundary
Content-Disposition: form-data; name="location"

pionerskaya
--MyBoundary
Content-Disposition: form-data; name="gender"

male
--MyBoundary
Content-Disposition: form-data; name="role"

user
--MyBoundary-

###
# Create coach.

POST http://localhost:5000/api/users/sign-up HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/png

< C:\Users\strim\Desktop\pro\avatar.jpg
--MyBoundary
Content-Disposition: form-data; name="name"

Виктория
--MyBoundary
Content-Disposition: form-data; name="email"

vika@hotmail.com
--MyBoundary
Content-Disposition: form-data; name="password"

123456
--MyBoundary
Content-Disposition: form-data; name="location"

petrogradskaya
--MyBoundary
Content-Disposition: form-data; name="gender"

female
--MyBoundary
Content-Disposition: form-data; name="role"

coach
--MyBoundary-

###
# Login user.

POST http://localhost:5000/api/users/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "123456"
}

###
# Get user by user ID.

GET http://localhost:5000/api/users/abc0c2b2-f617-40df-a542-75c54a245668 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyNjQxNjEsImV4cCI6MTc1MjI3NDk2MX0.vN7_-gxsWo--dWG1aCLmJvTlc4tN8YxXZ_9SCJCURsM
Content-Type: application/json

###
# Refresh token.

POST http://localhost:5000/api/users/refresh-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJ0b2tlbklkIjoiNDMxMzNiMGMtNTExYy00N2ViLTlmNDMtNGViNTQzNWE5OWI5IiwiaWF0IjoxNzUyMjY0MTYxLCJleHAiOjE3NTI4Njg5NjF9.2Gsyhk9czD1bZY_9vS5j2kHaGxKFR9_mg3eXXY6rvEU
Content-Type: application/json

###
# Check token.

POST http://localhost:5000/api/users/check-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMwYzJiMi1mNjE3LTQwZGYtYTU0Mi03NWM1NGEyNDU2NjgiLCJlbWFpbCI6InZva3NoaW5AeWEucnUiLCJpYXQiOjE3NTIyNjQxNjEsImV4cCI6MTc1MjI3NDk2MX0.vN7_-gxsWo--dWG1aCLmJvTlc4tN8YxXZ_9SCJCURsM
Content-Type: application/json

###
