export const BAD_MONGO_ID_ERROR = 'Неверный mongoID идентификатор.';
export const BAD_UUID_ERROR = 'Неверный UUID идентификатор.';
export const METADATA_PARAM_ERROR = 'Этот pipe должен использоваться только с "params".';
export const METADATA_CUSTOM_ERROR = 'Этот pipe должен использоваться только c "customs".';
export const METADATA_BODY_ERROR = 'Этот pipe должен использоваться только c "body".';
export const FORMAT_ERROR = 'Формат изображения должен быть jpeg или png.';
export const PARSE_DATA_ERROR = '[Недопустимый JSON]: %error%.'
export const SIZE_ERROR = 'Максимальный размер изображения 1 мегабайт';
export const MAX_SIZE = 1e+6;
